import React, { Component } from 'react';
import HeaderPage from '../Includes/Header'
import Footer from '../Includes/Footer'
import axios from 'axios';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import config from '../config/config';
import Cookies from 'js-cookie';
const headers = {
    'Content-Type': 'application/json'
};   

const initialState = {
    googleAuthCode: '',
}   

export default class googleAuth extends Component {

    constructor(props) {
        super(props)
        this.state = initialState
        this.onChange = this.onChange.bind(this);
        this.submitForm = this.submitForm.bind(this);       

        if(Cookies.get('user_id')){
            this.user_id = Cookies.get('user_id')
         }

    }

    componentDidMount() {

    }

    onChange(e) {
        this.setState({
            [e.target.name]: e.target.value
        })
    }    

    async submitForm(e) {
        e.preventDefault()
        this.setState(initialState)
        const data = this.state
        data.user_id = this.user_id
        delete this.state.passwordLength
        axios.post(`${config.apiUrl}/verifyAuthCode`, data, { headers })
            .then(response => {
                if (response.data.success === true) {
                    toast.success('Verified Successfully!', {
                        position: toast.POSITION.TOP_CENTER
                    });

                    setTimeout(() => {
                        Cookies.set('loginSuccess', response.data);
                        window.location.href = `${config.baseUrl}dashboard`
                    }, 2000);                    

                }

                else{
                    alert('sadf')
                    toast.error(response.data.msg, {
                        position: toast.POSITION.TOP_CENTER
                    });
                    // setTimeout(() => {
                    //     window.location.href = `${config.baseUrl}login`
                    // }, 2000);
                }
            })
            .catch(err => {            
                toast.error(err.response.data?.msg, {
                position: toast.POSITION.TOP_CENTER
                });
            })
    }      


    render() {

        return (
            <>
            <ToastContainer />
            <HeaderPage />
            <section className="buy-sell-tab">
                <div className="container">
                    <div className="row">
                    <div className="col-sm-4">
                        
                    </div>
                    <div className="col-sm-4">
                        <div id="content-block-login">
                    <div className="content-block">
                        <div className="inner text-center pt-2">
                            <img src={`${config.baseUrl}images/Esqro-Logo-B-1.png`} className="transition" alt="Esqro crypto" />
                            <h3 className="text-center head_theme pb-5">Google Authentication</h3>
                            <div className="form-signin-heading">
                            </div>
                            <form onSubmit={this.submitForm}> 
                                <div className="form-group">
                                Enter the verification code generated by Google Authenticator app on your phone.
                                    <input style={{height: "38px"}} onChange={this.onChange} value={this.state.email} className="form-control" placeholder="Enter Google Authenticator Code" type="number" name="googleAuthCode" id="email" />
                                    <label className="error"></label>
                                </div>                            
                  
                                <div className="form-group">
                                    {!this.state.googleAuthCode ?
                                    <button type="submit" className="btn btn-success pt-2 pb-2 col-sm-12 disabled_form" disabled >Submit</button>
                                    : <button type="submit" className="btn btn-success pt-2 pb-2 col-sm-12" >Submit</button>}
                                </div>
                                
                            </form>
                     
                            <br />
                            <div className="row">
                                <div className="col-md-12">
                                
                                </div>
                            </div>
                            
                        </div>
                        </div>
                        </div>
                    </div>
                    <div className="col-sm-4">
                        
                    </div>
                    
                    </div>
                    
                </div>
            </section>
            <Footer />
            </>
            )
        }
    }